baseURL = "https://stafura.dev/"
languageCode = "en-us"
title = "Matus Stafura"
theme = "berg"
enableRobotsTXT = true
defaultContentLanguage = "en"

[markup.highlight]
codeFences = true
lineNoStart = 1
noClasses = true
style = "rose-pine-moon"

[markup.tableOfContents]
startLevel = 2
endLevel = 3
ordered = false

[markup.goldmark]
renderer = { }

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5

[pagination]
pagerSize = 100

[params]
paginate = 5
date_format = "January 2, 2006"
custom_css = [ "css/_custom.css" ]
showDarkModeToggle = true
author = "Matus Stafura"
logo = "images/code.png"
favicon = "images/favicon/favicon.ico"

  [params.plugins]
  tagmanager = "GTM-N8KF2Q3"

  [params.posts]
  showPrevNext = true
  showDate = true
  showTags = true
  showCategories = true

[taxonomies]
tag = "tags"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/posts"
weight = 2

[[menu.main]]
name = "Portfolio"
url = "/portfolio"
weight = 3

[[menu.main]]
name = "About me"
url = "/about"
weight = 4

[[menu.main]]
name = "GitHub"
url = "https://github.com/matusstafura"
weight = 5
[menu.main.params]
    external = true

[[menu.footer]]
name = "Cookies"
url = "/cookies"
weight = 1

[[menu.footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 2
