baseURL = "https://stafura.dev/"
languageCode = "en-us"
title = "Matus Stafura"
theme = "themer"
enableRobotsTXT = true

[markup.goldmark.renderer]
hardWraps = true

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5

[Params]
date_format = "January 2, 2006"

  [Params.google]
  tagmanagerid = "GTM-N8KF2Q3"

[taxonomies]
tag = "tags"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/blogs"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "GitHub"
url = "https://github.com/matusstafura"
weight = 4

[[menu.footer]]
name = "Cookies"
url = "/cookies"
weight = 1

[[menu.footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 2
