name = "Aina"
license = "MIT"
licenselink = "https://github.com/matusstafura/aina-hugo-theme/blob/master/LICENSE"
description = "Ready to use responsive Hugo theme"
homepage = "https://github.com/matusstafura/aina-hugo-theme"
tags = []
features = ['responsive']
min_version = "0.92.0"

[author]
  name = "Matus Stafura"
  homepage = "https://github.com/matusstafura/aina-hugo-theme"
  